---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
  namespace: specificNamespace
rules:
  -
    apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - watch
      - list
      - update
      - delete
